name: Aktivitas terbaru workflow
on:
  schedule:
    # Runs every day
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-latest:
    name: Update this repo's README with latest activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update Aktivitas terbaru'